---
name: Text-Slidez
version: v0.0.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: format slideshows into XHTML
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Text-Slidez
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://svn.scratchcomputing.com/Text-Slidez/trunk
build_requires:
  Module::Build: 0.26
  Test::More: 0
requires:
  Class::Accessor::Classy: v0.9.1
  File::Fu: v0.0.6
  Getopt::AsDocumented: 0
  Shebangml: 0
  Text::VimColor: 0.11
  XML::Bits: 0
configure_requires:
  Module::Build: 0.34
provides:
  Text::Slidez:
    file: lib/Text/Slidez.pm
    version: v0.0.1
generated_by: Module::Build version 0.3406
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
